Testing serial input.

In [3]:
import serial
from serial.tools.list_ports import comports

In [4]:
comports()

In [152]:
detector = serial.Serial('/dev/cu.usbserial-00003014', baudrate=115200, timeout=1)

In [164]:
detector.reset_input_buffer()
rawdata=detector.read(1024)
datastring=rawdata.decode().split('\r\n')
print(datastring)

['3E8', '318', '318', '319', '319', '3E8', '318', '318', '318', '318', '318', '3E8', '318', '3E8', '318', '318', '319', '319', '3E8', '318', '318', '319', '318', '319', '3E8', '318', '3E8', '3E8', '318', '3E8', '3E8', '319', '318', '3E8', '319', '318', '318', '318', '318', '319', '3E8', '318', '319', '319', '3E8', '318', '3E8', '318', '3E8', '319', '318', '318', '319', '318', '318', '318', '319', '3E8', '319', '318', '318', '318', '3E8', '318', '3E8', '318', '318', '318', '3E8', '3E8', '318', '3E8', '318', '3E8', '318', '318', '318', '318', '318', '318', '318', '318', '318', '318', '318', '318', '318', '3E8', '318', '318', '318', '318', '318', '318', '3E8', '318', '317', '318', '318', '318', '317', '318', '318', '318', '318', '318', '317', '318', '318', '318', '318', '318', '3E8', '318', '318', '3E8', '318', '318', '3E8', '318', '3E8', '318', '318', '318', '318', '318', '3E8', '317', '318', '3E8', '318', '3E8', '3E8', '318', '3E8', '318', '318', '3E8', '318', '3E8', '318', '318', '318'

In [165]:
rawdata

b'3E8\r\n318\r\n318\r\n319\r\n319\r\n3E8\r\n318\r\n318\r\n318\r\n318\r\n318\r\n3E8\r\n318\r\n3E8\r\n318\r\n318\r\n319\r\n319\r\n3E8\r\n318\r\n318\r\n319\r\n318\r\n319\r\n3E8\r\n318\r\n3E8\r\n3E8\r\n318\r\n3E8\r\n3E8\r\n319\r\n318\r\n3E8\r\n319\r\n318\r\n318\r\n318\r\n318\r\n319\r\n3E8\r\n318\r\n319\r\n319\r\n3E8\r\n318\r\n3E8\r\n318\r\n3E8\r\n319\r\n318\r\n318\r\n319\r\n318\r\n318\r\n318\r\n319\r\n3E8\r\n319\r\n318\r\n318\r\n318\r\n3E8\r\n318\r\n3E8\r\n318\r\n318\r\n318\r\n3E8\r\n3E8\r\n318\r\n3E8\r\n318\r\n3E8\r\n318\r\n318\r\n318\r\n318\r\n318\r\n318\r\n318\r\n318\r\n318\r\n318\r\n318\r\n318\r\n318\r\n3E8\r\n318\r\n318\r\n318\r\n318\r\n318\r\n318\r\n3E8\r\n318\r\n317\r\n318\r\n318\r\n318\r\n317\r\n318\r\n318\r\n318\r\n318\r\n318\r\n317\r\n318\r\n318\r\n318\r\n318\r\n318\r\n3E8\r\n318\r\n318\r\n3E8\r\n318\r\n318\r\n3E8\r\n318\r\n3E8\r\n318\r\n318\r\n318\r\n318\r\n318\r\n3E8\r\n317\r\n318\r\n3E8\r\n318\r\n3E8\r\n3E8\r\n318\r\n3E8\r\n318\r\n318\r\n3E8\r\n318\r\n3E8\r\n318\r\n318\r\n318\

In [166]:
detector.close()

In [167]:
0x318

792

In [168]:
0x319

793

In [169]:
0x3e8

1000

In [320]:
0x005

5

In [175]:
import numpy as np
import re

In [188]:
np.frombuffer(datastring, dtype='|S3')

TypeError: a bytes-like object is required, not 'list'

In [218]:
data0 = np.frombuffer(re.sub(b'\r\n*', b'', rawdata), dtype='|S3')
data0

array([b'3E8', b'318', b'318', b'319', b'319', b'3E8', b'318', b'318',
       b'318', b'318', b'318', b'3E8', b'318', b'3E8', b'318', b'318',
       b'319', b'319', b'3E8', b'318', b'318', b'319', b'318', b'319',
       b'3E8', b'318', b'3E8', b'3E8', b'318', b'3E8', b'3E8', b'319',
       b'318', b'3E8', b'319', b'318', b'318', b'318', b'318', b'319',
       b'3E8', b'318', b'319', b'319', b'3E8', b'318', b'3E8', b'318',
       b'3E8', b'319', b'318', b'318', b'319', b'318', b'318', b'318',
       b'319', b'3E8', b'319', b'318', b'318', b'318', b'3E8', b'318',
       b'3E8', b'318', b'318', b'318', b'3E8', b'3E8', b'318', b'3E8',
       b'318', b'3E8', b'318', b'318', b'318', b'318', b'318', b'318',
       b'318', b'318', b'318', b'318', b'318', b'318', b'318', b'3E8',
       b'318', b'318', b'318', b'318', b'318', b'318', b'3E8', b'318',
       b'317', b'318', b'318', b'318', b'317', b'318', b'318', b'318',
       b'318', b'318', b'317', b'318', b'318', b'318', b'318', b'318',
      

In [253]:
idata = np.array([20 * int(n, 16) for n in data0])
idata

array([20000, 15840, 15840, 15860, 15860, 20000, 15840, 15840, 15840,
       15840, 15840, 20000, 15840, 20000, 15840, 15840, 15860, 15860,
       20000, 15840, 15840, 15860, 15840, 15860, 20000, 15840, 20000,
       20000, 15840, 20000, 20000, 15860, 15840, 20000, 15860, 15840,
       15840, 15840, 15840, 15860, 20000, 15840, 15860, 15860, 20000,
       15840, 20000, 15840, 20000, 15860, 15840, 15840, 15860, 15840,
       15840, 15840, 15860, 20000, 15860, 15840, 15840, 15840, 20000,
       15840, 20000, 15840, 15840, 15840, 20000, 20000, 15840, 20000,
       15840, 20000, 15840, 15840, 15840, 15840, 15840, 15840, 15840,
       15840, 15840, 15840, 15840, 15840, 15840, 20000, 15840, 15840,
       15840, 15840, 15840, 15840, 20000, 15840, 15820, 15840, 15840,
       15840, 15820, 15840, 15840, 15840, 15840, 15840, 15820, 15840,
       15840, 15840, 15840, 15840, 20000, 15840, 15840, 20000, 15840,
       15840, 20000, 15840, 20000, 15840, 15840, 15840, 15840, 15840,
       20000, 15820,

In [260]:
data0x = np.frombuffer(re.sub(b'\r\n*', b'', rawdata), dtype='|S3')
data_ns = np.array([20 * int(n, 16) for n in data0x])
data_ns

array([20000, 15840, 15840, 15860, 15860, 20000, 15840, 15840, 15840,
       15840, 15840, 20000, 15840, 20000, 15840, 15840, 15860, 15860,
       20000, 15840, 15840, 15860, 15840, 15860, 20000, 15840, 20000,
       20000, 15840, 20000, 20000, 15860, 15840, 20000, 15860, 15840,
       15840, 15840, 15840, 15860, 20000, 15840, 15860, 15860, 20000,
       15840, 20000, 15840, 20000, 15860, 15840, 15840, 15860, 15840,
       15840, 15840, 15860, 20000, 15860, 15840, 15840, 15840, 20000,
       15840, 20000, 15840, 15840, 15840, 20000, 20000, 15840, 20000,
       15840, 20000, 15840, 15840, 15840, 15840, 15840, 15840, 15840,
       15840, 15840, 15840, 15840, 15840, 15840, 20000, 15840, 15840,
       15840, 15840, 15840, 15840, 20000, 15840, 15820, 15840, 15840,
       15840, 15820, 15840, 15840, 15840, 15840, 15840, 15820, 15840,
       15840, 15840, 15840, 15840, 20000, 15840, 15840, 20000, 15840,
       15840, 20000, 15840, 20000, 15840, 15840, 15840, 15840, 15840,
       20000, 15820,

In [267]:
len(re.sub(b'\r\n*', b'', rawdata))

615

In [268]:
615/3

205.0

In [271]:
data_ns.size

205

In [276]:
if (614%3):
    print('Not 0')
else:
    print(0)

Not 0


In [308]:
ex = b'^[\dA-E]{1,2}\r|\n[\dA-E]{1,2}\r|\n[\dA-E]{1,2}\r$'

In [312]:
c = b'12\r\n1\r\n3E8\r\n1E4\r\n4\r'

In [313]:
re.sub(ex,b'X',c)

b'XX\n3E8\r\n1E4\rX'

In [314]:
datab=re.sub(b'\r\n*', b'', re.sub(ex, b'',rawdata))
datab

b'3E83183183193193E83183183183183183E83183E83183183193193E83183183193183193E83183E83E83183E83E83193183E83193183183183183193E83183193193E83183E83183E83193183183193183183183193E83193183183183E83183E83183183183E83E83183E83183E83183183183183183183183183183183183183183E83183183183183183183E83183173183183183173183183183183183173183183183183183E83183183E83183183E83183E83183183183183183E83173183E83183E83E83183E83183183E83183E83183183183173173183183183183183183E83183183183183E83183E83183183193E83183E83183183E83183183183E83E83E83183183E83183173E83183E83183173183E83193E83183183183183E83183E83193E83E83183E8318318318318318'

In [315]:
len(re.sub(b'\r\n*', b'', datab))/3

205.0

In [397]:
ex_3_digit = b'^[\dA-E]{1,2}\r|\n[\dA-E]{1,2}\r|\n[\dA-E]{1,2}\r$'
ex_cr_newline = b'\r\n*'
datab = re.sub(
    ex_cr_newline, 
    b'', 
    re.sub(ex_3_digit, b'', rawdata)
)
data0x = np.frombuffer(datab, dtype='|S3')
data_ns = np.array([20 * int(n, 16) for n in data0x])
data_ns

array([20000, 15840, 15840, 15860, 15860, 20000, 15840, 15840, 15840,
       15840, 15840, 20000, 15840, 20000, 15840, 15840, 15860, 15860,
       20000, 15840, 15840, 15860, 15840, 15860, 20000, 15840, 20000,
       20000, 15840, 20000, 20000, 15860, 15840, 20000, 15860, 15840,
       15840, 15840, 15840, 15860, 20000, 15840, 15860, 15860, 20000,
       15840, 20000, 15840, 20000, 15860, 15840, 15840, 15860, 15840,
       15840, 15840, 15860, 20000, 15860, 15840, 15840, 15840, 20000,
       15840, 20000, 15840, 15840, 15840, 20000, 20000, 15840, 20000,
       15840, 20000, 15840, 15840, 15840, 15840, 15840, 15840, 15840,
       15840, 15840, 15840, 15840, 15840, 15840, 20000, 15840, 15840,
       15840, 15840, 15840, 15840, 20000, 15840, 15820, 15840, 15840,
       15840, 15820, 15840, 15840, 15840, 15840, 15840, 15820, 15840,
       15840, 15840, 15840, 15840, 20000, 15840, 15840, 20000, 15840,
       15840, 20000, 15840, 20000, 15840, 15840, 15840, 15840, 15840,
       20000, 15820,

In [399]:
data_temp = data_ns.copy()

In [400]:
data_temp

array([20000, 15840, 15840, 15860, 15860, 20000, 15840, 15840, 15840,
       15840, 15840, 20000, 15840, 20000, 15840, 15840, 15860, 15860,
       20000, 15840, 15840, 15860, 15840, 15860, 20000, 15840, 20000,
       20000, 15840, 20000, 20000, 15860, 15840, 20000, 15860, 15840,
       15840, 15840, 15840, 15860, 20000, 15840, 15860, 15860, 20000,
       15840, 20000, 15840, 20000, 15860, 15840, 15840, 15860, 15840,
       15840, 15840, 15860, 20000, 15860, 15840, 15840, 15840, 20000,
       15840, 20000, 15840, 15840, 15840, 20000, 20000, 15840, 20000,
       15840, 20000, 15840, 15840, 15840, 15840, 15840, 15840, 15840,
       15840, 15840, 15840, 15840, 15840, 15840, 20000, 15840, 15840,
       15840, 15840, 15840, 15840, 20000, 15840, 15820, 15840, 15840,
       15840, 15820, 15840, 15840, 15840, 15840, 15840, 15820, 15840,
       15840, 15840, 15840, 15840, 20000, 15840, 15840, 20000, 15840,
       15840, 20000, 15840, 20000, 15840, 15840, 15840, 15840, 15840,
       20000, 15820,

In [402]:
timeouts = np.flip(np.argwhere(data_ns==20000).flatten())
prev = timeouts[0]
count = 1
indlist = np.array([], dtype=np.int)
countlist = np.array([], dtype=np.int)
for val in timeouts[1:]:
    if val == prev - 1:
        count += 1
    else:
        indlist = np.insert(indlist, 0, prev)
        if count == 1:
            countlist = np.insert(countlist, 0, 40000)
        else:
            countlist = np.insert(countlist, 0, 40000+count)
        count = 1
    prev = val
indlist = np.insert(indlist, 0, prev)
if count == 1:
    countlist = np.insert(countlist, 0, 40000)
else:
    countlist = np.insert(countlist, 0, 40000+count)

In [403]:
indlist

array([  0,   5,  11,  13,  18,  24,  26,  29,  33,  40,  44,  46,  48,
        57,  62,  64,  68,  71,  73,  87,  94, 112, 115, 118, 120, 126,
       129, 131, 134, 137, 139, 151, 156, 158, 162, 164, 167, 171, 176,
       179, 181, 185, 187, 192, 194, 196, 199])

In [405]:
indlist.size

47

In [406]:
data_temp.size - indlist.size

158

In [407]:
countlist

array([40000, 40000, 40000, 40000, 40000, 40000, 40002, 40002, 40000,
       40000, 40000, 40000, 40000, 40000, 40000, 40000, 40002, 40000,
       40000, 40000, 40000, 40000, 40000, 40000, 40000, 40000, 40000,
       40002, 40000, 40000, 40000, 40000, 40000, 40000, 40000, 40000,
       40000, 40003, 40000, 40000, 40000, 40000, 40000, 40000, 40000,
       40002, 40000])

In [408]:
data_ns[indlist] = countlist

In [409]:
data_ns[data_ns!=20000].size

198

In [410]:
data_temp.size

205

In [411]:
data_ns[data_ns<20000]

array([15840, 15840, 15860, 15860, 15840, 15840, 15840, 15840, 15840,
       15840, 15840, 15840, 15860, 15860, 15840, 15840, 15860, 15840,
       15860, 15840, 15840, 15860, 15840, 15860, 15840, 15840, 15840,
       15840, 15860, 15840, 15860, 15860, 15840, 15840, 15860, 15840,
       15840, 15860, 15840, 15840, 15840, 15860, 15860, 15840, 15840,
       15840, 15840, 15840, 15840, 15840, 15840, 15840, 15840, 15840,
       15840, 15840, 15840, 15840, 15840, 15840, 15840, 15840, 15840,
       15840, 15840, 15840, 15840, 15840, 15840, 15840, 15840, 15840,
       15820, 15840, 15840, 15840, 15820, 15840, 15840, 15840, 15840,
       15840, 15820, 15840, 15840, 15840, 15840, 15840, 15840, 15840,
       15840, 15840, 15840, 15840, 15840, 15840, 15840, 15840, 15820,
       15840, 15840, 15840, 15840, 15840, 15840, 15840, 15840, 15840,
       15820, 15820, 15840, 15840, 15840, 15840, 15840, 15840, 15840,
       15840, 15840, 15840, 15840, 15840, 15840, 15860, 15840, 15840,
       15840, 15840,

In [412]:
data_ns[data_ns<20000].size

151

In [413]:
data_temp[data_temp<20000].size

151

In [414]:
import time

In [417]:
tstamp = int(time.time())

In [426]:
tstamp * np.ones(data_ns.size, dtype=np.int)

array([1580785399, 1580785399, 1580785399, 1580785399, 1580785399,
       1580785399, 1580785399, 1580785399, 1580785399, 1580785399,
       1580785399, 1580785399, 1580785399, 1580785399, 1580785399,
       1580785399, 1580785399, 1580785399, 1580785399, 1580785399,
       1580785399, 1580785399, 1580785399, 1580785399, 1580785399,
       1580785399, 1580785399, 1580785399, 1580785399, 1580785399,
       1580785399, 1580785399, 1580785399, 1580785399, 1580785399,
       1580785399, 1580785399, 1580785399, 1580785399, 1580785399,
       1580785399, 1580785399, 1580785399, 1580785399, 1580785399,
       1580785399, 1580785399, 1580785399, 1580785399, 1580785399,
       1580785399, 1580785399, 1580785399, 1580785399, 1580785399,
       1580785399, 1580785399, 1580785399, 1580785399, 1580785399,
       1580785399, 1580785399, 1580785399, 1580785399, 1580785399,
       1580785399, 1580785399, 1580785399, 1580785399, 1580785399,
       1580785399, 1580785399, 1580785399, 1580785399, 1580785

In [435]:
output = np.concatenate(([data_ns], [tstamp * np.ones(data_ns.size, dtype=np.int)]), axis=0).T

In [437]:
np.savetxt('temp', output, fmt='%d')

In [439]:
f = open('temp', 'a')
np.savetxt(f, output, fmt='%d')
f.close()